apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dry2mcqyk-python 
  janus-idp.io/tekton: dry2mcqyk-python
  backstage.io/kubernetes-id: dry2mcqyk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dry2mcqyk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml