apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dry2mcqyk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dry2mcqyk-python 
  name: dry2mcqyk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dry2mcqyk-python 
